// Add typings for SVG component generated by SVGR
// https://react-svgr.com/
declare module '*.svg' {
    import React from 'react';

    const component: React.FC<React.SVGAttributes<SVGElement>>;
    export default component;
}
